//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public Agency()
        {
            this.Coupons = new HashSet<Coupon>();
            this.Packages = new HashSet<Package>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsInternational { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
    }
}
