//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public Coupon()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int Discount { get; set; }
        public int AddedBy { get; set; }
        public Nullable<int> SponsoredBy { get; set; }
        public System.DateTime ExpireOn { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
