//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PackageId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UsedCoupon { get; set; }
        public int Paid { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Package Package { get; set; }
        public virtual User User { get; set; }
    }
}
